/**
 * @ingroup gr_GUI
 */
class GUILabel
{
  public:
   float x;
   float y;
   float width;
   float height;
   bool scaleChilds;
   bool Reference_Units;
   bool alignByParent;
   int horz_align;
   int vert_align;
   int weight;
   bool clip_childs;
   int text_align;
   int vrt_text_align;
   float alpha;
   float anchor_x;
   float anchor_y;
   bool AnchAbsUnits;
   float rotation;
   bool CellMove;
   bool AllowMouseCover;
   bool autoRecalc;
   float fontScale;
   bool fontUseShd;
   float URL_fade_in;
   bool ScriptedDraw;
   float tileHorzOffset;
   float tileVertOffset;
   float tileHorz;
   float tileVert;
   int tileType;
   bool IsVisible();
   void Show(bool show);
   bool IsActive();
   void Activate(bool Active);
   void SetTransformPos(Vector&in pos);
   void GetTransformPos(Vector&out pos);
   void GetType(string&out name);
   void GetData(string&out name);
   void SetData(string&in name);
   float GetScreenX();
   float GetScreenY();
   float GetScreenWidth();
   float GetScreenHeight();
   void SetParent(string&in name);
   void SetText(string&in name);
   void GetText(string&out name);
   float get_width();
   void set_width(float w);
   float get_height();
   void set_height(float h);
   float get_alpha();
   void set_alpha(float set_alpha);
   float get_x();
   void set_x(float set_x);
   float get_y();
   void set_y(float set_y);
   void SetFocused(bool set_focused);
   bool IsFocused();
   void RecalcPos();
   float GetTextWidth(string&in txt);
   float GetTextHeight(string&in txt);
   void SetColor(float r, float g, float b);
   void SetSkin(string&in txt);
   void Draw(float x, float y);
   void Draw(float x, float y, float wdt, float hgt, float alpha, float rotate);
   void Draw(float x, float y, float wdt, float hgt, float alpha, float rotate, float u, float v, float du, float dv);
   void DrawTexArray(int index, float set_x, float set_y, float wdt, float hgt, float alpha, float rotate);
   void DrawTexArray(int index, float set_x, float set_y, float wdt, float hgt, float alpha, float rotate, float u, float v, float du, float dv);
   void DrawSkined(int index, float set_x, float set_y, float wdt, float hgt, float alpha, float rotate);
   void DrawText(float x, float y, string&in txt_text, float alpha);
   void DrawText(float x, float y, float w, float h, string&in txt_text, float alpha);
   void DrawText(float x, float y, float w, float h, float font_scale, string&in txt_text, float alpha);
   void DrawTextCached(float x, float y, int index, float alpha);
   void DrawTextCached(float x, float y, float w, float h, int index, float alpha);
   void DrawTextCached(float x, float y, float w, float h, float font_scale, int index, float alpha);
   void SetTexture(string&in texture);
   void SetTextureURL(string&in url);
   void GetTextureFileName(string&out name);
   bool IsTextureLoading();
   void SetFontColor(float r, float g, float b);
   void SetFontShadowColor(float r, float g, float b);
   void SetTextureInArray(int index, string&in txt);
   void SetTextureURLInArray(int index, string&in url);
   void GetTextureFileNameInArray(int index, string&out name);
   void ResizeTextureArray(int count);
   int  GetTextureArraySize();
   bool IsTextureLoadingInArray(int count);
   void RestartTexture();
   void PauseTexture(bool pause);
   void PauseTextureInArrayScript(int index, bool pause);
   void RestartTextureInArrayScript(int index, bool pause);
   float GetTextureDuration();
   int GetTextureWidth();
   int GetTextureHeight();
   int GetTextureWidthInArray(int index);
   int GetTextureHeightInArray(int index);
   void ClearCachedStrings();
   void ResizeCachedStrings(int size);
   int  GetCachedStringsCount();
   void AddCachedString(string& str);
   void SetCachedString(int index, string& str);
   void DelCachedString(int index);
   void set_fontScale(float s);
   float get_fontScale();
};
