/**
 * @ingroup gr_NGUI
 */
class NGUILabel
{
  public:
   float x;
   float y;
   float width;
   float height;
   float rot_x;
   float rot_y;
   float rot_z;
   bool scaleChilds;
   bool alignByParent;
   int horz_align;
   int vert_align;
   bool clip_childs;
   int text_align;
   int vrt_text_align;
   float alpha;
   float anchor_x;
   float anchor_y;
   bool AnchAbsUnits;
   bool CellMove;
   bool AllowMouseCover;
   bool filled;
   float filled_alpha;
   int num_visible_lines;
   bool selection_enable;
   int text_cursor_width;
   int text_cursor_height;
   bool UseEntity;
   float fontScale;
   bool UseEntity2;
   float URL_fade_in;
   bool IsVisible();
   void Show(bool show);
   bool IsActive();
   void Activate(bool Active);
   void SetTransformPos(Vector&in pos);
   void GetTransformPos(Vector&out pos);
   void GetType(string&out name);
   void GetData(string&out name);
   void SetData(string&in name);
   float GetAbsoluteX();
   float GetAbsoluteY();
   void SetText(string&in name);
   void GetText(string& name);
   float get_x();
   void set_x(float set_x);
   float get_y();
   void set_y(float set_y);
   float get_width();
   void set_width(float w);
   float get_height();
   void set_height(float h);
   float get_alpha();
   void set_alpha(float set_alpha);
   float get_rot_x();
   void set_rot_x(float set_rot_x);
   float get_rot_y();
   void set_rot_y(float set_rot_y);
   float get_rot_z();
   void set_rot_z(float set_rot_z);
   void SetFocused(bool set_focused);
   bool IsFocused();
   float GetCurTextWidth();
   float GetCurTextHeight();
   int GetCurTextLinesCount();
   float GetTextWidth(string&in txt);
   float GetTextHeight(string&in txt);
   int GetTextLinesCount(string&in txt);
   void SetColor(float r, float g, float b);
   void SetColor(string&in txt);
   void GetColor(float& r, float& g, float& b);
   void GetName(string& nm);
   int GetIndexInParentChilds();
   void SetIndexInParentChilds(int index);
   NGUIWidget@ GetChild(string&in name);
   NGUIWidget@ GetChild(int index);
   int GetChildCount();
   NGUIWidget@ opImplCast();
   NGUILabel@ opCast();
   void SetTexture(string&in texture);
   void SetTextureURL(string&in url);
   void GetTextureFileName(string& name);
   bool IsTextureLoading();
   void SetFontColor(float r, float g, float b);
   void GetFontColor(float& r, float& g, float& b);
   void SetFontShadowColor(float r, float g, float b);
   void RestartTexture();
   void PauseTexture(bool pause);
   float GetTextureDuration();
   void EnableTextureCameraFeed(bool pause);
   int GetTextureWidth();
   int GetTextureHeight();
   void set_fontScale(float s);
   float get_fontScale();
   void SetTextureUV(float u, float v, float du, float dv);
   void SetScriptMaskUV(float u, float v, float du, float dv);
   void SetFontName(string&in name, bool bold, bool italic, int size, float gap, float outline);
   void SetSelectionEnable(bool bSet);
   void SetSelectionColor(float r, float g, float b,float a);
   void SetCursorsColor(float r, float g, float b,float a);
   void SetFilled(bool flag);
   bool IsFilled();
   void SetFilledColor(float r, float g, float b,float a);
   void SetFilledColor(string&in txt);
   void GetFilledColor(float& r, float& g, float& b, float& a);
   void SetDelegate(NGUILabelDelegate@ delegate);
};
