/**
 * @ingroup gr_NGUI
 */
class NGUITimeSelector
{
  public:
   float x;
   float y;
   float width;
   float height;
   float rot_x;
   float rot_y;
   float rot_z;
   bool scaleChilds;
   bool alignByParent;
   int horz_align;
   int vert_align;
   bool clip_childs;
   int text_align;
   int vrt_text_align;
   float alpha;
   float anchor_x;
   float anchor_y;
   bool AnchAbsUnits;
   bool CellMove;
   bool AllowMouseCover;
   float ElementHeigth;
   int ElementsCount;
   bool AllowDate;
   bool AmPmMode;
   bool TimeLine;
   int MinutesStep;
   int MaxHour;
   int MaxMinute;
   int MinHour;
   int MinMinute;
   bool BackgroundUseEntity;
   bool SelectedBackgroundUseEntity;
   bool IsVisible();
   void Show(bool show);
   bool IsActive();
   void Activate(bool Active);
   void SetTransformPos(Vector&in pos);
   void GetTransformPos(Vector&out pos);
   void GetType(string&out name);
   void GetData(string&out name);
   void SetData(string&in name);
   float GetAbsoluteX();
   float GetAbsoluteY();
   void SetText(string&in name);
   void GetText(string& name);
   float get_x();
   void set_x(float set_x);
   float get_y();
   void set_y(float set_y);
   float get_width();
   void set_width(float w);
   float get_height();
   void set_height(float h);
   float get_alpha();
   void set_alpha(float set_alpha);
   float get_rot_x();
   void set_rot_x(float set_rot_x);
   float get_rot_y();
   void set_rot_y(float set_rot_y);
   float get_rot_z();
   void set_rot_z(float set_rot_z);
   void SetFocused(bool set_focused);
   bool IsFocused();
   float GetCurTextWidth();
   float GetCurTextHeight();
   int GetCurTextLinesCount();
   float GetTextWidth(string&in txt);
   float GetTextHeight(string&in txt);
   int GetTextLinesCount(string&in txt);
   void SetColor(float r, float g, float b);
   void SetColor(string&in txt);
   void GetColor(float& r, float& g, float& b);
   void GetName(string& nm);
   int GetIndexInParentChilds();
   void SetIndexInParentChilds(int index);
   NGUIWidget@ GetChild(string&in name);
   NGUIWidget@ GetChild(int index);
   int GetChildCount();
   NGUIWidget@ opImplCast();
   NGUITimeSelector@ opCast();
   void SetDayText(int index, string&in text);
   void SetMonthText(int index, string&in text);
   void SetAmPmText(int index, string&in text);
   void SetTime(int hour,int minute);
   void ClearTimeIntervals();
   void AddTimeInterval(int hourMin,int minuteMin,int hourMax,int minuteMax);
   void SetMaxTime(int hour,int minute);
   void SetMinTime(int hour,int minute);
   void SetDate(int day,int month,int year);
   void SetMinuteStep(int step);
   void SetAmPmMode(bool bSet);
   void SetDateMode(bool bSet);
   void GetSelectedDate(int&out day, int&out month, int&out year);
   void GetSelectedTime(int&out hour, int&out minute);
   bool IsTimeValid();
   void SetTimesColor(float r, float g, float b);
   void SetSelectedTimeColor(float r, float g, float b);
   void SetNotValidTimeColor(float r, float g, float b);
   void SetDelegate(NGUITimeSelectorDelegate@ delegate);
};
