/**
 * @ingroup gr_NGUI
 */
class NGUICalendar
{
  public:
   float x;
   float y;
   float width;
   float height;
   float rot_x;
   float rot_y;
   float rot_z;
   bool scaleChilds;
   bool alignByParent;
   int horz_align;
   int vert_align;
   bool clip_childs;
   int text_align;
   int vrt_text_align;
   float alpha;
   float anchor_x;
   float anchor_y;
   bool AnchAbsUnits;
   bool CellMove;
   bool AllowMouseCover;
   bool AllowPast;
   bool AutoSelectCurDate;
   bool allowScroll;
   int Theme;
   bool ShowWeekDays;
   float topSize;
   float captionSize;
   float cellSize;
   float monthGap;
   float nextBtnSize;
   float markerSize;
   bool IsVisible();
   void Show(bool show);
   bool IsActive();
   void Activate(bool Active);
   void SetTransformPos(Vector&in pos);
   void GetTransformPos(Vector&out pos);
   void GetType(string&out name);
   void GetData(string&out name);
   void SetData(string&in name);
   float GetAbsoluteX();
   float GetAbsoluteY();
   void SetText(string&in name);
   void GetText(string& name);
   float get_x();
   void set_x(float set_x);
   float get_y();
   void set_y(float set_y);
   float get_width();
   void set_width(float w);
   float get_height();
   void set_height(float h);
   float get_alpha();
   void set_alpha(float set_alpha);
   float get_rot_x();
   void set_rot_x(float set_rot_x);
   float get_rot_y();
   void set_rot_y(float set_rot_y);
   float get_rot_z();
   void set_rot_z(float set_rot_z);
   void SetFocused(bool set_focused);
   bool IsFocused();
   float GetCurTextWidth();
   float GetCurTextHeight();
   int GetCurTextLinesCount();
   float GetTextWidth(string&in txt);
   float GetTextHeight(string&in txt);
   int GetTextLinesCount(string&in txt);
   void SetColor(float r, float g, float b);
   void SetColor(string&in txt);
   void GetColor(float& r, float& g, float& b);
   void GetName(string& nm);
   int GetIndexInParentChilds();
   void SetIndexInParentChilds(int index);
   NGUIWidget@ GetChild(string&in name);
   NGUIWidget@ GetChild(int index);
   int GetChildCount();
   NGUIWidget@ opImplCast();
   NGUICalendar@ opCast();
   void GetSelectedDate(int&out day, int&out month, int&out year);
   void MarkDate(bool mark, int day, int month, int year);
   bool IsDayMarked(int day, int month, int year);
   void ClearMarkedDays();
   void SetCurrentDate(int day, int month, int year);
   void SetSelectedDate(int day, int month, int year);
   void AddForbidedDate(bool mark, int day, int month, int year);
   bool IsDayForbided(int day, int month, int year);
   void ClearForbidedDays();
   void GetNextDay(int day, int month, int year, int&out out_day, int&out out_month, int&out out_year);
   void GetPrevDay(int day, int month, int year, int&out out_day, int&out out_month, int&out out_year);
   void SetMonthText(int index, string&in text);
   void SetDayText(int index, string&in text);
   void SetTopFontColor(float r, float g, float b);
   void SetCaptionFontColor(float r, float g, float b);
   void SetCellFontColor(float r, float g, float b);
   void SetCellSelFontColor(float r, float g, float b);
   void SetCellPrevFontColor(float r, float g, float b);
   void SetTopTexColor(float r, float g, float b);
   void SetLineTexColor(float r, float g, float b);
   void SetCellTexColor(float r, float g, float b);
   void SetCellSelTexColor(float r, float g, float b);
   void SetMarkedTexColor(float r, float g, float b);
   void SetMarkedPrevTexColor(float r, float g, float b);
   void SetDelegate(NGUICalendarDelegate@ delegate);
};
