/**
 * @ingroup gr_scriptcore_parts
 */
class SceneScriptCoreUtils
{
  public:
   float Rnd();
   void GetRayDir(Vector& pos, Vector& dir);
   void GetScreenPos(Vector&in pos, Vector& screen_pos);
   void GetCamDir(Vector& dir);
   float GetHour();
   float GetMinute();
   float GetSecond();
   float GetDay();
   float GetMonth();
   float GetYear();
   int64 GetSystemTime();
   int ParseUnixTime(int index, uint64 time);
   void GetDateTimeUTC(int& year, int& month, int& day, int& hour, int& min, int& sec);
   int64 GetTimestamp(int year, int month, int day, int hour, int min, int sec);
   int GetWeekOfDay(int day, int month, int year);
   float GetFps();
   int CalcUtf8Len(string& text);
   void ClampUtf8(string&in text, string& res, int clamp_len);
   void ConvertASCIIToUTF8(string&in wstr, string& str);
   void Int64ToString(int64 val, string& str);
   void UInt64ToString(uint64 val, string& str);
   void GetMD5Hash(string&in str, string& hash);
   void GetUID(string&in postfix, string& uid);
   void GetISO8601DateTime(string& str);
   void GetISO8601DateTimeForAzureQuerry(string& str);
   void ExtractFileName(string&in FullPath, string& FileName);
   void OpenURL(string&in url, bool inner);
   void OpenURL(string&in url, string&in stop_url);
   void OpenVideo(string&in path, string&in showName);
   void OpenVideo(string&in path);
   void StartMonitoringRegion(string&in id, string&in uuid);
   void StopMonitoringRegion(string&in id);
   void SetCallbackOnEnterRegion(string&in id, string&in func);
   void SetCallbackOnExitRegion(string&in id, string&in func);
   int GetRegionBeaconsCount(string&in id);
   int GetRegionBeaconMinor(string&in id, int index);
   int GetRegionBeaconMajor(string&in id, int index);
   int GetRegionBeaconProximity(string&in id, int index);
   float GetRegionBeaconDistance(string&in id, int index);
   void HTMLToText(string& in, string& out);
   void LowerCase(string& in, string& out);
   void UpperCase(string& in, string& out);
   void Replace(string& str, string&in find, string&in replace);
   void PrintTextOnPhoto(string&in text, string&in input_photo,  string&in output_photo, string&in output_ext);
   void PrintCallStack();
   void CopyFile(string& src, string& dest);
   float QuadraticEaseIn(float f);
   float QuadraticEaseOut(float f);
   float QuadraticEaseInOut(float f);
   float CubicEaseIn(float f);
   float CubicEaseOut(float f);
   float CubicEaseInOut(float f);
   float QuarticEaseIn(float f);
   float QuarticEaseOut(float f);
   float QuarticEaseInOut(float f);
   float QuinticEaseIn(float f);
   float QuinticEaseOut(float f);
   float QuinticEaseInOut(float f);
   float SineEaseIn(float f);
   float SineEaseOut(float f);
   float SineEaseInOut(float f);
   float CircularEaseIn(float f);
   float CircularEaseOut(float f);
   float CircularEaseInOut(float f);
   float ExponentialEaseIn(float f);
   float ExponentialEaseOut(float f);
   float ExponentialEaseInOut(float f);
   float ElasticEaseIn(float f);
   float ElasticEaseOut(float f);
   float ElasticEaseInOut(float f);
   float BackEaseIn(float f);
   float BackEaseOut(float f);
   float BackEaseInOut(float f);
   float BounceEaseIn(float f);
   float BounceEaseOut(float f);
   float BounceEaseInOut(float f);
   int64 GetInstallTime();
};
